### ISSUE TITLE
Automatically comment if edits were made to the docs folder

### ISSUE THREAD

**Issue by BastianZim** [conda-forge/conda-forge.github.io#1458]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hi everybody,

this came up a couple of times during the outreach application process but I only had the time now.
In short, there were some cases where edits were made to the docs folder and not the scr one. Each time, someone from core had to manually tell the author to change their contributions and I'm thinking that this could probably be automated.
As I'm not sure if conda-forge wants to keep that human touch, I just wanted to preliminarily open this issue to see if there's an openness to have this automated or not.

The easiest implementation would probably be a GitHub action like this:

```yaml
on:
  pull_request_target:
    types: [opened]
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hi, thanks for improving the conda-forge docs. Unfortunately, the edit was made in the _docs_ folder and not in the _src_ folder. \nPlease only edit the _src_ folder as the HTML is automatically generated after merging. For more information, visit the [conda-forge docs](https://conda-forge.org/docs/user/contributing.html#improve-the-documentation).'
            })
```
