### ISSUE TITLE
Mark packages which intentionally not build on a certain system

### ISSUE THREAD

**Issue by jankatins** [conda-forge/conda-forge.github.io#151]
the problem I want to solve is that I don't know if a feedstock disabled windows build because noone built a `bld.bat` yet or because the package is not needed/buildable on windows.

My proposal would be to put the following in the 

``` yaml
extra:
    not-building-on: 
         - win  # reason why it doesn't build (name = identifier in the "skip  # [...]")
         - py2k  # project doesn't support it anymore
```

Examples: 
- [antispoofing.utils](https://github.com/conda-forge/antispoofing.utils-feedstock/blob/master/recipe/meta.yaml#L17): I had to follow the links to https://github.com/idiap/bob/wiki/Binary-Installation to see that it seems to have no windows builds.
- [feather-fomat](https://github.com/conda-forge/feather-format-feedstock/blob/master/recipe/meta.yaml#L13) on the other hand should be buildable on windows, at least there is a R binary package on CRAN.
- [caffe](https://github.com/conda-forge/caffe-feedstock/blob/master/recipe/meta.yaml#L16) is kind of inbetween: It seems to be not supported, but it is buildable: https://github.com/BVLC/caffe/wiki/Installation#windows, https://github.com/BVLC/caffe/issues/15

This would also help to prevent the ugly missing icon on https://conda-forge.github.io/feedstocks.html
