### ISSUE TITLE
Wide-spread conda-build breakage due to conda 4.13 in windows CI

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge.github.io#1762]
In windows CI, the base conda version actually comes from an azure pipelines task (in `azure-pipelines-win.yml`):
```
    - task: CondaEnvironment@1
      inputs:
        packageSpecs: 'python=3.9 conda-build conda pip boa conda-forge-ci-setup=3' # Optional
        installOptions: "-c conda-forge"
        updateConda: true
      displayName: Install conda-build and activate environment
```

I'm not 100% sure this is intentional, but windows builds started picking up conda 4.13 (which conda-forge hasn't packaged [yet](https://github.com/conda-forge/conda-feedstock/pull/165)) sometime in the last hours, which also happened to remove some py27 compat code that was relied upon by conda-build, see https://github.com/conda/conda-build/issues/4481.

Thankfully, there's been a swift [fix](https://github.com/conda/conda-build/pull/4482) (not yet merged, much less released). I backported it in https://github.com/conda-forge/conda-build-feedstock/pull/176 (where I ran into the same error I'm trying to fix, but managed a work-around).

I think this should be merged soon-to-ASAP to limit the fall-out, but considering how we're picking the unpackaged conda 4.13 in the windows CI setup, I'm not actually sure now this would make a difference. In that case we might need to hotfix something like https://github.com/conda-forge/conda-build-feedstock/pull/176/commits/412fdfc7f4ef5f7b1dbeabeb60209969805db72b into conda-smithy for the time being...?

CC @conda-forge/core
