### ISSUE TITLE
How to not include shared library to package dependencies?

### ISSUE THREAD

**Issue by isaevil** [conda-forge/conda-forge.github.io#1829]
### Your question:

Hi, I want to build package with on of its libraries to be linked dynamically with `libhwloc`. So I added `libhwloc` to `host` requirements for linkage to work on `aarch64` and `ppc64le`. 
```yaml
requirements:
   build:
       - {{ compiler('cxx') }}
       - cmake
       - make
       - pkg-config
   host:
       - libhwloc
```
But I would not like the library to be installed with my package while doing `conda install <package>` because my library works like plugin.
I wasn't familiar with conda recipes before and I don't actually know is there some mechanism to do so?
