### ISSUE TITLE
Add bot directive to remove a patch on a new release 

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/conda-forge.github.io#2036]
### Your question:

What happens from time-to-time is that a minor bug appears in an already released version (e.g. [here](https://github.com/conda-forge/fmt-feedstock/pull/38)). A nice option for the feedstock is to add a patch. However, this adds a maintenance burden as the patch has to be removed on the next release. It would be nice to have the bot do this.

For example:
```yaml
{% set version = "10.1.1" %}

source:
   url: https://github.com/fmtlib/fmt/archive/{{ version }}.tar.gz
   sha256: {{ sha256 }}
   patches:
     - patches/0001-fix-core-version-10.1.1.patch   # [delete >{{ version }}]
```
Upon upgrading to 10.1.2 (or any version higher than 10.1.1) the bot could then remove the patch from `meta.yaml` and remove the patch file.
