### ISSUE TITLE
Is pin_compatible("numpy") still the recommended way of dealing with numpy after introduction of the new backwards compatiple C-API?

### ISSUE THREAD

**Issue by maxnoe** [conda-forge/conda-forge.github.io#2037]
### Your question:

Numpy 1.25 introduced a backwards compatible C-API with a definable minimum supported numpy version.

For a project defining `-DNPY_TARGET_VERSION NPY_1_21_API_VERSION` one could thus I think do:

```
requirements:
    build:
        - numpy >=1.25 # 1.25 needed for backwards-compatible C-API
    host:
        - numpy >=1.25 # 1.25 needed for backwards-compatible C-API
    run:
        - numpy >=1.21 # But result will be compatible with all version larger than NPY_TARGET_VERSION
```

Given this new mechanism, is `{{ pin_compatible("numpy") }}` still the way to go? 

If not, we should update the knowledge base section on numpy.
