### ISSUE TITLE
`run_exports` in MPI example

### ISSUE THREAD

**Issue by njzjz** [conda-forge/conda-forge.github.io#2039]
### Where should the content be changed?

https://conda-forge.org/docs/maintainer/knowledge_base.html#complete-example

### What should be changed?

https://github.com/conda-forge/conda-forge.github.io/blob/abb0e2e8af66f5fb667e8e11d6d12f2a82604638/src/maintainer/knowledge_base.rst?plain=1#L803-L806

I am wondering why there is no package exported for the `nompi` package.

I think it should be corrected to

```yaml
    {% if mpi != 'nompi' %}
    run_exports:
      - {{ name }} * {{ mpi_prefix }}_*
    {% endif %}
    {% if mpi == 'nompi' %}
    run_exports:
      - {{ name }}
    {% endif %}
```

Or, if the package should not be exported, `run_constrained` should be used instead of `run_exports`:

```yaml
    {% if mpi != 'nompi' %}
    run_constrained:
      - {{ name }} * {{ mpi_prefix }}_*
    {% endif %}
```

### Additional information

Originally submitted in https://github.com/conda-forge/plumed-feedstock/issues/36, but I noticed it just copies the documentation.

### Incorrect or outdated

- [X] Incorrect
- [ ] Outdated
