### ISSUE TITLE
How to increase the Windows Azure memory

### ISSUE THREAD

**Issue by mgovers** [conda-forge/conda-forge.github.io#2462]
### Your question:

I can't find documentation on how to increase the (actual or virtual) RAM size for the Azure runners. What is the best way to do this?

### The issue

In our builds for the PGM project for Windows, we are regularly running into the message

```log
##[warning]Free memory is lower than 5%; Currently used: 96.87%
```

[Recently](https://github.com/conda-forge/power-grid-model-feedstock/pull/323#event-16342382823), it is sometimes also followed by the following fatal error:

```log
fatal error C1060: compiler is out of heap space
```

See e.g. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=1179341&view=logs&j=e5f486ac-cae9-516a-6014-708581034f38&t=91748b1d-6c83-5a76-0eaf-45eee90cf754&l=1267

The reason is quite obvious, but I am not sure how to fix this.

### What I did find

I did find in the https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure and https://raw.githubusercontent.com/conda-forge/conda-smithy/main/conda_smithy/data/conda-forge.json the following settings

```yaml
azure:
    settings_win:
        variables:
            SET_PAGEFILE: "True"
            CONDA_BLD_PATH: "C:\bld"
            MINIFORGE_HOME: "C:\Miniforge"
```

However, this is also guarded by the disclaimer "This is usually read-only and should not normally be manually modified. Tools like conda-smithy may modify this, as needed."

Is this the right solution?
