### ISSUE TITLE
Testing packages with GUIs

### ISSUE THREAD

**Issue by hajapy** [conda-forge/conda-forge.github.io#399]
Is it possible to investigate enabling X virtual framebuffers on Circle CI and Travis CI so that we can write tests that utilize a graphical user interface? 

I bring this up because I recently came across an [issue with the opencv package](https://github.com/conda-forge/opencv-feedstock/issues/79). Essentially, with the latest builds  cv2.imshow() worked on OS X (build picks up Cocoa bindings automatically), but fails to function on Linux (and probably Windows) because highgui doesn't get compiled unless a gui library is specifically configured for the build (eg. Qt or VTK). Although I proposed [a PR to fix this](https://github.com/conda-forge/opencv-feedstock/pull/81), the GUI isn't actually tested so I have no quick way to ensure the builds are good until after they are released. 

I dug around to try to figure out how one might begin to instrument tests that use a graphical interface. Here is a summary of my findings:

**Circle CI**, would need to add to our circle.yml
```
- run:
    name: Running X virtual framebuffer
    command: Xvfb :99 -screen 0 1280x1024x24
    background: true
```

**Travic CI,** taken from [here](https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI)
 
The docs say this:
```
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
	- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
```

[This guide ](https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md) says it could be just this:
```
addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
```

**AppVeyor**, I think a virtual framebuffer is present to begin with and nothing special is needed. 

Given that testing all these changes is beyond my expertise and would affect all conda-forge builds, I leave it to more experienced hands to look into.
