### ISSUE TITLE
py2k and noarch

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#486]
It might be nice to opt out of python 2k in noarch, since 2k is winding down and newer packages may not support it outright but otherwise meet the noarch criteria. (Of course this will also help to lighten the CI load)
In discussion with @scopatz

**Comment by jjhelmus** [comment]
`noarch: packages` can be created with Python specification, including requiring python >= 3.  As an example here is a recipe for a `noarch: python` version of glob2 which would only be installable in Python 3 environments:

``` yaml
{% set name = "glob2" %}
{% set version = "0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5b0a686ff21f820c4d3f0c4edd216704cea59d79d00fa337e244a2f2ff83ed6

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3
    - setuptools
  run:
    - python >=3

test:
  imports:
    - glob2
```

Note that glob2 does support Python 2.7 so there is no need to limit the package in this manner, it is only an example.

**Comment by jjhelmus** [comment]
I don't see how changing `noarch: python` packages to exclude Python 2 would result in a savings in CI time. AFAIK only a single build is done for `noarch: python` packages.  

For "standard" packages skipping Python 2.7 builds would save time.  This can be done already by adding `skip: True  # [py27]` to the build section of the `meta.yaml`.  I think the option of building or not building for Python 2.7 should be left in the hands of the recipes maintainers.

**Comment by CJ-Wright** [comment]
I was only asking for the *option* to exclude Python 2. The savings would come from being able to run python 3 only builds with noarch. Currently a python 3 only build has to build on every CI, so this enhancement would reduce CI load.

I don't think that the above recipe would work, having tried that kind of solution [here](https://circleci.com/gh/conda-forge/regolith-feedstock/16?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

**Comment by jakirkham** [comment]
Also might be worth looking at PR ( https://github.com/conda/conda-build/pull/2487 ), which would test this functionality in `conda-build`.

**Comment by jakirkham** [comment]
Should add that selectors are still not possible for `noarch` packages. So if there are Python version specific dependencies, this would not be an option.

**Comment by isuruf** [comment]
Another option is to create a meta package `meta-python3` which is built only for Python 3 and have it as a run dependency

**Comment by isuruf** [comment]
@CJ-Wright, I don't think your issue is related to this. Maybe noarch doesn't handle script files very well. You might have better luck using entrypoints.

**Comment by jjhelmus** [comment]
@CJ-Wright From the testing I've done the `regolith` recipe can be converted to `noarch: python` with a `- python >=3.5` requirement specification when using conda-build 3.x.  The build fails with conda-build 2.1.17.  Removing the python constraint results in a successful build, but is obviously not desired.  I have not been able to track down the source of the failure, but conda/conda-build#1962 may be involved.

**Comment by mbargull** [comment]
Using the changes from https://github.com/conda/conda-build/pull/2672 I can build the `regolith` recipe just fine with
```yaml
build:
  noarch: python
...
requirements:
  build:
    - python >=3
...
  run:
    - python >=3
```
