### ISSUE TITLE
add bot info to meta.yaml

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge.github.io#564]
It might be good to allow users to insert info into `extra` under `autotick-bot`. For example 
```yaml
extra:
  autotick-bot:
    blacklist: True
```
Would blacklist the feedstock from the bot (the bot would keep track of the meta.yaml but it wouldn't issue PRs).
