### ISSUE TITLE
Disable building/running a specific version

### ISSUE THREAD

**Issue by zerothi** [conda-forge/conda-forge.github.io#603]
I am trying to fix my feedstock and stumpled upon a bug in one of the dependencies.
This bug is however only present in one version of the dependency package.

So how can I *disable* a specific version.

I tried:

```yaml
host:
   scipy <1.1.0,>1.1.0
```
which failed with `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"scipy[version='<1.1.0,>1.1.0']"}`.

However, I would have liked something like:
```yaml
host:
   scipy !=1.1.0
```
which would have been better suited, and something similar in `pin_compatible`. My current solution is this:

```yaml
host:
    - scipy <=1.0.0
  run:
    - {{ pin_compatible('scipy', upper_bound='1.1.0') }}
```
which I also don't think is good.
