### ISSUE TITLE
Adding organization info to extra

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge.github.io#72]
This was [raised]( https://github.com/conda-forge/staged-recipes/pull/235/files/c4a062e4eab1c8c525bf2e215a25d4ba51adf9c1#r57901637 ) by a contributor that felt it was very important to list the organization that was maintaining the recipe. @ocefpaf proposed the spec below. Seems like we should discuss and agree on some strategy if organizations should be included.

```yaml
extra:
  recipe-maintainers:
    - 183amir
  github-organization:
    - bioidiap
```
