### ISSUE TITLE
document use of run_constrained

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge.github.io#756]
IDK if we need to document this, but we have been using `run_constrained` to help eliminate package conflicts. 

@chrisburr for viz and further comments.

Here is an example:

```yaml
requirements:
  run_constrained:
    - pypy3.5 ==99999999999  # thing that conflicts with current package
```
