### ISSUE TITLE
Installer for Aarch64 (and ppc64le)

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge.github.io#871]
Now that the aarch migration is well underway, it seems like it would be to create a `Miniconda` installer for `aarch64`

Not too sure why this one is not working
https://github.com/Archiconda/build-tools/issues/23

**Comment by jjhelmus** [comment]
I'd be in favor of this.  The question is where to host the installer?  Perhaps a GitHub release would be reasonable with a link to the installer from the conda-forge.org.

**Comment by mariusvniekerk** [comment]
Github release seems prudent.

**Comment by isuruf** [comment]
@hmaarfk, let us know what we can do to help like creating a github repo, activating a CI, etc.

**Comment by jakirkham** [comment]
Thoughts @msarahan?

**Comment by hmaarrfk** [comment]
`Jewlerconda3/construct.yaml`

```yaml
# what to call this???
name: Jewlerconda3
version: 0.1.0

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/anaconda
  # There still seems to be a dependency needed from c4aarch64
  - https://conda.anaconda.org/c4aarch64

write_condarc: True
#license_file: installer_license.txt

specs:
  - python 3.7.3
  - conda
  - pip
```

**Comment by mariusvniekerk** [comment]
forge-conda?

**Comment by hadim** [comment]
An aarch64 flavor of conda provided by Anaconda or conda-forge would indeed be super nice. Any news or ETA on this? What does remain to be done? Anything I can do to help.

In the meantime, I use Archiconda which does the job well.

**Comment by hmaarrfk** [comment]
somebody needs to test it on real metal hardware.

I got  RPi4, but still haven't had a chance to connect it to a monitor.

**Comment by hadim** [comment]
I just tested the last Archiconda3 installer on an Rpi4 with Ubuntu 19.10 arm64 and it works perfectly.

I couldn't installed either update conda because of an issue with the university network here (DNS won't resolve) but I'll report once it works.

**Comment by hadim** [comment]
Waiting for the DNS issue to be solved I tried to build an installer with the packages I need:

```yaml
name: Archiconda
version: 0.3.0

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/anaconda
  # There still seems to be a dependency needed from c4aarch64
  - https://conda.anaconda.org/c4aarch64

write_condarc: True

specs:
  - python
  - conda
  - pip
  - numpy
  - scipy
  - pandas
  - sqlalchemy
  - pyserial
  - slacker
```

```bash
constructor --platform=linux-aarch64 .
```

I built it on my host machine (Ubuntu x86_64) but when trying the installation on RPi 4 I have the following error:

```bash
$ bash Archiconda-0.3.0-Linux-aarch64.sh 

Welcome to Archiconda 0.3.0

Archiconda will now be installed into this location:
/home/ubuntu/archiconda

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/ubuntu/archiconda] >>> 
PREFIX=/home/ubuntu/archiconda
Unpacking payload ...
Archiconda-0.3.0-Linux-aarch64.sh: line 259: /home/ubuntu/archiconda/conda.exe: cannot execute binary file: Exec format error
ERROR: could not extract tar starting at offset 000000000000011467+9231072+2
```

I guess it's because the installer is x86_64 only compatible. Any idea of how I could build an installer that works on arm64? Docker (but then how do you initially install `constructor` without `conda`)?

Also, I noticed a pretty important package is not available yet for arm64: `matplotlib`. I open an issue about it: https://github.com/conda-forge/matplotlib-feedstock/issues/221
